CREATE TABLE LIEU (
    ID NUMBER(10) PRIMARY KEY,
    NOM VARCHAR2(100)
);

CREATE TABLE "TYPE" (
    ID NUMBER(10) NOT NULL PRIMARY KEY,
    NOM VARCHAR2(100), 
    DESCRIPTION VARCHAR2(1000)
);

CREATE TABLE SITE (
    ID NUMBER(10) NOT NULL PRIMARY KEY,
    LIEU_ID NUMBER(10),
    NOM VARCHAR2(100),
    CONSTRAINT FK_LIEU FOREIGN KEY (LIEU_ID) REFERENCES LIEU(ID)
);

CREATE TABLE EQUIPEMENT (
    ID NUMBER(10) NOT NULL PRIMARY KEY,
    NOM VARCHAR2(100),
    TYPE_ID NUMBER(10),
    LIEU_ID NUMBER(10),
    SITE_ID NUMBER(10),
    CONSTRAINT FK_TYPE FOREIGN KEY (TYPE_ID) REFERENCES "TYPE"(ID),
    CONSTRAINT FK_LIEU FOREIGN KEY (LIEU_ID) REFERENCES LIEU(ID),
    CONSTRAINT FK_SITE FOREIGN KEY (SITE_ID) REFERENCES SITE(ID)
);

CREATE TABLE UTILISATEURS (
    ID NUMBER(10) NOT NULL PRIMARY KEY,
    NOM VARCHAR2(100),
    PRENOM VARCHAR2(100),
    EMAIL VARCHAR2(100),
    SITE_ID NUMBER(10),
    CONSTRAINT FK_SITE_USER FOREIGN KEY (SITE_ID) REFERENCES SITE(ID)
);

CREATE TYPE STATUS AS ENUM ('en cours', 'ouvert', 'fermé');

CREATE TABLE TICKETS (
    ID NUMBER(10) NOT NULL PRIMARY KEY,
    NOM VARCHAR2(10),
    EQUIPEMENT_ID NUMBER(10),
    CREATION_DATE DATE,
    USER_ID NUMBER(10),
    ISSUE_DESCRIPTION VARCHAR2(1000),
    SITE_ID NUMBER(10),
    STATUS STATUS,
    CONSTRAINT FK_EQUIPEMENT FOREIGN KEY (EQUIPEMENT_ID) REFERENCES EQUIPEMENT(ID),
    CONSTRAINT FK_USER_TICKET FOREIGN KEY (USER_ID) REFERENCES UTILISATEURS(ID),
    CONSTRAINT FK_SITE_TICKET FOREIGN KEY (SITE_ID) REFERENCES SITE(ID)
);
