

CREATE TABLE GLPI_LIEU (
    ID NUMBER(10) NOT NULL PRIMARY KEY,
    NOM VARCHAR2(100)
);

CREATE TABLE GLPI_TYPE (
    ID NUMBER(10) NOT NULL PRIMARY KEY,
    NOM VARCHAR2(100), 
    DESCRIPTION VARCHAR2(1000)
);

CREATE TABLE GLPI_SITE (
    ID NUMBER(10) NOT NULL PRIMARY KEY,
    LIEU_ID NUMBER(10),
    NOM VARCHAR2(100),
    CONSTRAINT FK_SITE_LIEU FOREIGN KEY (LIEU_ID) REFERENCES GLPI_LIEU(ID)
);

CREATE TABLE GLPI_EQUIPEMENT (
    ID NUMBER(10) NOT NULL PRIMARY KEY,
    NOM VARCHAR2(100),
    TYPE_ID NUMBER(10),
    LIEU_ID NUMBER(10),
    SITE_ID NUMBER(10),
    CONSTRAINT FK_TYPE FOREIGN KEY (TYPE_ID) REFERENCES GLPI_TYPE(ID),
    CONSTRAINT FK_EQUIPEMENT_LIEU FOREIGN KEY (LIEU_ID) REFERENCES GLPI_LIEU(ID),
    CONSTRAINT FK_SITE FOREIGN KEY (SITE_ID) REFERENCES GLPI_SITE(ID)
);

CREATE TABLE GLPI_UTILISATEUR (
    ID NUMBER(10) NOT NULL PRIMARY KEY,
    NOM VARCHAR2(100),
    PRENOM VARCHAR2(100),
    EMAIL VARCHAR2(100),
    SITE_ID NUMBER(10),
    CONSTRAINT FK_SITE_UTILISATEUR FOREIGN KEY (SITE_ID) REFERENCES GLPI_SITE(ID)
);

CREATE TABLE GLPI_TICKET (
    ID NUMBER(10) NOT NULL PRIMARY KEY,
    NOM VARCHAR2(10),
    EQUIPEMENT_ID NUMBER(10),
    CREATION_DATE DATE,
    UTILISATEUR_ID NUMBER(10),
    DESCRIPTION VARCHAR2(1000),
    SITE_ID NUMBER(10),
    STATUT VARCHAR2(20) CONSTRAINT staut_check CHECK (STATUT IN ('en cours', 'ouvert', 'fermé')),
    CONSTRAINT FK_TICKETS_EQUIPEMENT FOREIGN KEY (EQUIPEMENT_ID) REFERENCES GLPI_EQUIPEMENT(ID),
    CONSTRAINT FK_UTILISATEUR_TICKET FOREIGN KEY (UTILISATEUR_ID) REFERENCES GLPI_UTILISATEUR(ID),
    CONSTRAINT FK_SITE_TICKET FOREIGN KEY (SITE_ID) REFERENCES GLPI_SITE(ID)
);


-- Vérifier qu'à l'insertion, les dates correspondent
CREATE TABLE GLPI_LOCATION (
    ID NUMBER(10) NOT NULL PRIMARY KEY,
    EQUIPEMENT_ID NUMBER(10),
    CONSTRAINT FK_LOCATION_EQUIPEMENT FOREIGN KEY (EQUIPEMENT_ID) REFERENCES GLPI_EQUIPEMENT(ID),
    DEBUT DATE,
    FIN DATE
);
