CREATE ROLE "CERGY Admin";
CREATE ROLE "CERGY User";
CREATE ROLE "CERGY Technicien";

GRANT ALL PRIVILEGES TO "CERGY Admin";

GRANT SELECT, DELETE, UPDATE ON GLPI_LIEU TO "CERGY Technicien";
GRANT SELECT, DELETE, UPDATE ON GLPI_TYPE TO "CERGY Technicien";
GRANT SELECT, DELETE, UPDATE ON GLPI_SITE TO "CERGY Technicien";
GRANT SELECT, DELETE, UPDATE ON GLPI_EQUIPEMENT TO "CERGY Technicien";
GRANT SELECT, DELETE, UPDATE ON GLPI_UTILISATEUR TO "CERGY Technicien";
GRANT SELECT, DELETE, UPDATE ON GLPI_TICKET TO "CERGY Technicien";
GRANT SELECT, DELETE, UPDATE ON GLPI_LOCATION TO "CERGY Technicien";

CREATE ROLE "PAU Admin";
CREATE ROLE "PAU User";
CREATE ROLE "PAU Technicien";

GRANT ALL PRIVILEGES TO "PAU Admin";

GRANT SELECT, DELETE, UPDATE ON GLPI_LIEU TO "PAU Technicien";
GRANT SELECT, DELETE, UPDATE ON GLPI_TYPE TO "PAU Technicien";
GRANT SELECT, DELETE, UPDATE ON GLPI_SITE TO "PAU Technicien";
GRANT SELECT, DELETE, UPDATE ON GLPI_EQUIPEMENT TO "PAU Technicien";
GRANT SELECT, DELETE, UPDATE ON GLPI_UTILISATEUR TO "PAU Technicien";
GRANT SELECT, DELETE, UPDATE ON GLPI_TICKET TO "PAU Technicien";
GRANT SELECT, DELETE, UPDATE ON GLPI_LOCATION TO "PAU Technicien";

CREATE ROLE "GLOBAL Admin";

GRANT ALL PRIVILEGES TO "GLOBAL Admin";

GRANT "CERGY Admin", "CERGY User", "CERGY Technicien", "PAU Admin", "PAU User", "PAU Technicien", "GLOBAL Admin" TO glpi;
