BEGIN
    DELETE FROM GLPI_TICKET;
    DELETE FROM GLPI_LOCATION;
    
    DELETE FROM GLPI_EQUIPEMENT;
    DELETE FROM GLPI_UTILISATEUR;
    
    DELETE FROM GLPI_SITE;
    DELETE FROM GLPI_LIEU;
    DELETE FROM GLPI_TYPE;
END;

COMMIT;
