DROP TABLE GLPI_TICKET CASCADE CONSTRAINTS;
DROP TABLE GLPI_UTILISATEUR CASCADE CONSTRAINTS;
DROP TABLE GLPI_EQUIPEMENT CASCADE CONSTRAINTS;
DROP TABLE GLPI_SITE CASCADE CONSTRAINTS;
DROP TABLE GLPI_TYPE CASCADE CONSTRAINTS;
DROP TABLE GLPI_LIEU CASCADE CONSTRAINTS;
