ALTER SESSION SET "_ORACLE_SCRIPT"=true;
DROP TABLESPACE glpi_data INCLUDING CONTENTS AND DATAFILES;
DROP USER glpi CASCADE;
DROP USER glpi_pau CASCADE;
DROP USER cergy_admin CASCADE;
DROP USER cergy_technicien CASCADE;
DROP USER cergy_utilisateur CASCADE;
DROP USER glpi_cergy CASCADE;
DROP USER pau_admin CASCADE;
DROP USER pau_technicien CASCADE;
DROP USER pau_utilisateur CASCADE;
DROP ROLE cergy_admin_role;
DROP ROLE cergy_technicien_role;
DROP ROLE cergy_utilisateur_role;
DROP ROLE pau_admin_role;
DROP ROLE pau_technicien_role;
DROP ROLE pau_utilisateur_role;