CREATE INDEX index_glpi_site_lieu_id ON GLPI_SITE (LIEU_ID);
CREATE INDEX index_glpi_equipement_type_id ON GLPI_EQUIPEMENT (TYPE_ID);
CREATE INDEX index_glpi_equipement_lieu_id ON GLPI_EQUIPEMENT (LIEU_ID);
CREATE INDEX index_glpi_equipement_site_id ON GLPI_EQUIPEMENT (SITE_ID);
CREATE INDEX index_glpi_utilisateur_site_id ON GLPI_UTILISATEUR (SITE_ID);
CREATE INDEX index_glpi_ticket_equipement_id ON GLPI_TICKET (EQUIPEMENT_ID);
CREATE INDEX index_glpi_ticket_utilisateur_id ON GLPI_TICKET (UTILISATEUR_ID);
CREATE INDEX index_glpi_ticket_site_id ON GLPI_TICKET (SITE_ID);
CREATE INDEX index_glpi_location_equipement_id ON GLPI_LOCATION (EQUIPEMENT_ID);
COMMIT;