ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER glpi IDENTIFIED BY glpi;
GRANT CONNECT, RESOURCE, DBA TO glpi;
CONNECT glpi/glpi;
ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER glpi_cergy IDENTIFIED BY glpi_cergy;
CREATE USER glpi_pau IDENTIFIED BY glpi_pau;
GRANT CONNECT, RESOURCE TO glpi_cergy;
GRANT CONNECT, RESOURCE TO glpi_pau;

SET TIMING ON;
SET linesize 250;
